export const environment = {
  production: false,
  useLocalJson: true,
  APP_NAME: 'LazySuzy',
  JSON_BASE_HREF: 'assets/resources/',
  ADMIN_API_BASE_HREF: 'http://staging.lazysuzy.com:8081/api/admin/',
  API_BASE_HREF: 'http://localhost:4444/api/',
  BASE_HREF: 'http://localhost:4444',
  SITE_URL: 'http://localhost:4200',
  ES_API_BASE_HREF: 'https://www.lazysuzy.com:9200/',
  LIVE_SITE: true,
  GOOGLE_LINK: 'https://www.lazysuzy.com/redirect/google',
  FACEBOOK_LINK: 'https://www.lazysuzy.com/redirect/facebook',
  BOARD_BASE_HREF: 'board',
  STRIPE_API_KEY: 'pk_test_0QKsReaTyej3eaewGR3HWiqZ00CzWWFs34',
};
