import { Injectable } from '@angular/core';
import { BehaviorSubject, Subject, Observable, of } from 'rxjs';
import { ApiService } from 'src/app/shared/services';

@Injectable({
    providedIn: 'root'
})
export class AdminDashboardService {

    private adminDashboardState: BehaviorSubject<any> = new BehaviorSubject({});
    unsubscribe$: Subject<boolean> = new Subject();

    constructor(public apiService: ApiService) { }

    getProducts(category, appliedFilters, pageNo): Observable<any> {
        // return this.apiService.getBrowseTabData(category.LS_ID, appliedFilters, pageNo);
        return of({
            "seo_data":{
               "page_title":"Chairs & Ottomans",
               "full_title":"Kids Chairs",
               "email_title":"Kids Chairs",
               "description":"Search hundreds of Chairs & Ottomans from top brands at once. Add to your room designs with your own design boards.",
               "image_url":"https:\/\/www.lazysuzy.com\/images\/product-category\/kids\/Seating_full.jpg"
            },
            "total":211,
            "constructor_count":0,
            "sortType":[
               {
                  "name":"Recommended",
                  "value":"recommended",
                  "enabled":false
               },
               {
                  "name":"Popularity",
                  "value":"popularity",
                  "enabled":false
               },
               {
                  "name":"Price: Low to High",
                  "value":"price_low_to_high",
                  "enabled":false
               },
               {
                  "name":"Price: High to Low",
                  "value":"price_high_to_low",
                  "enabled":false
               }
            ],
            "limit":24,
            "filterData":{
               "brand":[
                  {
                     "name":"CB2",
                     "value":"cb2",
                     "enabled":false,
                     "checked":false,
                     "count":0
                  },
                  {
                     "name":"Crate&Barrel",
                     "value":"cab",
                     "enabled":true,
                     "checked":false,
                     "count":211
                  },
                  {
                     "name":"Pier1",
                     "value":"pier1",
                     "enabled":true,
                     "checked":false,
                     "count":3
                  },
                  {
                     "name":"West Elm",
                     "value":"westelm",
                     "enabled":false,
                     "checked":false,
                     "count":0
                  },
                  {
                     "name":"World Market",
                     "value":"nw",
                     "enabled":false,
                     "checked":false,
                     "count":0
                  }
               ],
               "price":{
                  "from":36,
                  "to":1699,
                  "max":1699,
                  "min":35.97
               },
               "type":[
                  {
                     "name":"Chairs",
                     "value":"chairs",
                     "enabled":true,
                     "checked":false,
                     "count":155
                  },
                  {
                     "name":"Benches",
                     "value":"benches",
                     "enabled":true,
                     "checked":false,
                     "count":9
                  },
                  {
                     "name":"Ottomans",
                     "value":"ottomans",
                     "enabled":true,
                     "checked":false,
                     "count":68
                  }
               ],
               "color":[
                  {
                     "name":"Black",
                     "value":"black",
                     "hex":"#000000",
                     "enabled":false,
                     "checked":false
                  },
                  {
                     "name":"Blue",
                     "value":"blue",
                     "hex":"#0000ee",
                     "enabled":false,
                     "checked":false
                  },
                  {
                     "name":"Brown",
                     "value":"brown",
                     "hex":"#a52a2a",
                     "enabled":true,
                     "checked":false
                  },
                  {
                     "name":"Clear",
                     "value":"clear",
                     "hex":"#dcf0ef",
                     "enabled":true,
                     "checked":false
                  },
                  {
                     "name":"Copper",
                     "value":"copper",
                     "hex":"#b87333",
                     "enabled":false,
                     "checked":false
                  },
                  {
                     "name":"Gold",
                     "value":"gold",
                     "hex":"#FFD700",
                     "enabled":true,
                     "checked":false
                  },
                  {
                     "name":"Green",
                     "value":"green",
                     "hex":"#008000",
                     "enabled":true,
                     "checked":false
                  },
                  {
                     "name":"Grey",
                     "value":"grey",
                     "hex":"#808080",
                     "enabled":true,
                     "checked":false
                  },
                  {
                     "name":"Multicolor",
                     "value":"multicolor",
                     "hex":"#eeeeee",
                     "enabled":true,
                     "checked":false
                  },
                  {
                     "name":"Pink",
                     "value":"pink",
                     "hex":"#FFC0CB",
                     "enabled":true,
                     "checked":false
                  },
                  {
                     "name":"Purple",
                     "value":"purple",
                     "hex":"#800080",
                     "enabled":false,
                     "checked":false
                  },
                  {
                     "name":"Red",
                     "value":"red",
                     "hex":"#FF0000",
                     "enabled":false,
                     "checked":false
                  },
                  {
                     "name":"Silver",
                     "value":"silver",
                     "hex":"#C0C0C0",
                     "enabled":false,
                     "checked":false
                  },
                  {
                     "name":"Tan",
                     "value":"tan",
                     "hex":"#d2b48c",
                     "enabled":false,
                     "checked":false
                  },
                  {
                     "name":"White",
                     "value":"white",
                     "hex":"#ffffff",
                     "enabled":true,
                     "checked":false
                  }
               ],
               "category":null,
               "seating":[
                  {
                     "name":"2 seats",
                     "value":"2 seats",
                     "count":0,
                     "enabled":false,
                     "checked":false
                  },
                  {
                     "name":"4 seats",
                     "value":"4 seats",
                     "count":0,
                     "enabled":false,
                     "checked":false
                  },
                  {
                     "name":"6 seats",
                     "value":"6 seats",
                     "count":0,
                     "enabled":false,
                     "checked":false
                  },
                  {
                     "name":"8 seats",
                     "value":"8 seats",
                     "count":0,
                     "enabled":false,
                     "checked":false
                  }
               ],
               "shape":[
         
               ]
            },
            "products":[
                {
                  "id":5,
                  "sku":"387873",
                  "is_new":false,
                  "redirect":false,
                  "in_inventory":false,
                  "inventory_product_details":null,
                  "site":"Crate&Barrel",
                  "name":"Large Furry Sheep Bean Bag Chair",
                  "product_url":"https:\/\/www.crateandbarrel.com\/large-furry-sheep-bean-bag-chair\/s387873",
                  "product_detail_url":"https:\/\/www.lazysuzy.com\/product\/387873",
                  "is_price":"109.97",
                  "was_price":"169",
                  "percent_discount":"34.93",
                  "model_code":"",
                  "seating":null,
                  "color":"",
                  "collection":"",
                  "condition":"",
                  "main_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/isimageCrateFurrySheepBeanBagChrLgHLSHF19FurrySheepBeanBagChrLgHLSHF19",
                  "reviews":0,
                  "rating":0,
                  "wishlisted":false,
                  "variations":[
                     {
                        "product_sku":"387873",
                        "variation_sku":"387873",
                        "name":"Cover and Insert",
                        "has_parent_sku":true,
                        "swatch_image":null,
                        "image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/isimageCrateFurrySheepBeanBagChrLgHLSHF19FurrySheepBeanBagChrLgHLSHF19",
                        "link":"\/product\/387873",
                        "is_button":true,
                        "label":"Cover and Insert"
                     },
                     {
                        "product_sku":"387873",
                        "variation_sku":"387855",
                        "name":"Cover",
                        "has_parent_sku":false,
                        "swatch_image":null,
                        "image":null,
                        "link":"\/product\/387873",
                        "is_button":true,
                        "label":"Cover"
                     }
                  ]
               },
               {
                  "id":5,
                  "sku":"370015",
                  "is_new":false,
                  "redirect":false,
                  "in_inventory":false,
                  "inventory_product_details":null,
                  "site":"Crate&Barrel",
                  "name":"Large Blue Triangle Nod Chair",
                  "product_url":"https:\/\/www.crateandbarrel.com\/large-blue-triangle-nod-chair\/s370015",
                  "product_detail_url":"https:\/\/www.lazysuzy.com\/product\/370015",
                  "is_price":"139",
                  "was_price":"139",
                  "percent_discount":"0.00",
                  "model_code":"",
                  "seating":null,
                  "color":"",
                  "collection":"",
                  "condition":"",
                  "main_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/isimageCrateNodChairBlueTriangleLgHLSHF19NodChairBlueTriangleLgHLSHF19",
                  "reviews":210,
                  "rating":4.4238,
                  "wishlisted":false,
                  "variations":[
                     {
                        "product_sku":"370015",
                        "variation_sku":"369956",
                        "name":"Blue Triangle",
                        "has_parent_sku":false,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairBlueTriangleLgSHF19_zmGRweb_HWGrouperThumb200513130358NodChairBlueTriangleLgSHF19_zmGR.jpgNodChairBlueTriangleLgSHF19_zmGR.jpg",
                        "image":null,
                        "link":"\/product\/370015",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"369814",
                        "name":"Pink Confetti",
                        "has_parent_sku":false,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairPinkConfettiLgHLSHF19_zmGRweb_HWGrouperThumb200516055916NodChairPinkConfettiLgHLSHF19_zmGR.jpgNodChairPinkConfettiLgHLSHF19_zmGR.jpg",
                        "image":null,
                        "link":"\/product\/370015",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"369873",
                        "name":"Grey Stripe",
                        "has_parent_sku":false,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairGreyStripeLrgHLSHF19_zmGRweb_HWGrouperThumb200513040501NodChairGreyStripeLrgHLSHF19_zmGR.jpgNodChairGreyStripeLrgHLSHF19_zmGR.jpg",
                        "image":null,
                        "link":"\/product\/370015",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"303211",
                        "name":"Grey",
                        "has_parent_sku":false,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairGreyLrgAVF19_zmGRweb_HWGrouperThumb200516060032NodChairGreyLrgAVF19_zmGR.jpgNodChairGreyLrgAVF19_zmGR.jpg",
                        "image":null,
                        "link":"\/product\/370015",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"304993",
                        "name":"Dark Blue",
                        "has_parent_sku":true,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairDrkBlueLrgAVF19_zmGRweb_HWGrouperThumb200516060032NodChairDrkBlueLrgAVF19_zmGR.jpgNodChairDrkBlueLrgAVF19_zmGR.jpg",
                        "image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/isimageCrateNodChairDrkBlueLrgPRSHF19NodChairDrkBlueLrgPRSHF19",
                        "link":"\/product\/304993",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"305055",
                        "name":"Mint",
                        "has_parent_sku":true,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairMintLrgAVF19_zmGRweb_HWGrouperThumb200516040951NodChairMintLrgAVF19_zmGR.jpgNodChairMintLrgAVF19_zmGR.jpg",
                        "image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/isimageCrateNodChairMintLrgPRSHF19NodChairMintLrgPRSHF19",
                        "link":"\/product\/305055",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"305107",
                        "name":"Light Purple",
                        "has_parent_sku":true,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairLtPurpleLrgAVF19_zmGRweb_HWGrouperThumb200516060032NodChairLtPurpleLrgAVF19_zmGR.jpgNodChairLtPurpleLrgAVF19_zmGR.jpg",
                        "image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/isimageCrateNodChairLtPurpleLrgPRSHF19NodChairLtPurpleLrgPRSHF19",
                        "link":"\/product\/305107",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"305038",
                        "name":"Pink",
                        "has_parent_sku":true,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairPinkLrgAVF19_zmGRweb_HWGrouperThumb200516055916NodChairPinkLrgAVF19_zmGR.jpgNodChairPinkLrgAVF19_zmGR.jpg",
                        "image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/isimageCrateNodChairPinkLrgPRSHF19NodChairPinkLrgPRSHF19",
                        "link":"\/product\/305038",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"303331",
                        "name":"Dark Green",
                        "has_parent_sku":false,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairDrkGreenLrgAVF19_zmGRweb_HWGrouperThumb200516060032NodChairDrkGreenLrgAVF19_zmGR.jpgNodChairDrkGreenLrgAVF19_zmGR.jpg",
                        "image":null,
                        "link":"\/product\/370015",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"305098",
                        "name":"Orange",
                        "has_parent_sku":true,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairOrangeLrgAVF19_zmGRweb_HWGrouperThumb200516040952NodChairOrangeLrgAVF19_zmGR.jpgNodChairOrangeLrgAVF19_zmGR.jpg",
                        "image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/isimageCrateNodChairOrangeLrgPRSHF19NodChairOrangeLrgPRSHF19",
                        "link":"\/product\/305098",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"552814",
                        "name":"Light Green",
                        "has_parent_sku":false,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images\/Swatch_Soft_Goods_Nod_Chair_Executive_MI_SC.jpg",
                        "image":null,
                        "link":"\/product\/370015",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"624812",
                        "name":"Dark Grey Outer Space",
                        "has_parent_sku":true,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/OuterSpaceNodChrLrgPrsSHF18_zmGRweb_HWGrouperThumb200513130358OuterSpaceNodChrLrgPrsSHF18_zmGR.jpgOuterSpaceNodChrLrgPrsSHF18_zmGR.jpg",
                        "image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/isimageCrateOuterSpaceGreyNodChairLrgSHF18OuterSpaceGreyNodChairLrgSHF18",
                        "link":"\/product\/624812",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"369936",
                        "name":"Grey Stripe",
                        "has_parent_sku":true,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairGreyStripeLrgHLSHF19_zmGRweb_HWGrouperThumb200516060132NodChairGreyStripeLrgHLSHF19_zmGR.jpgNodChairGreyStripeLrgHLSHF19_zmGR.jpg",
                        "image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/isimageCrateNodChairGreyStripeLrgHLAVPRSHF19NodChairGreyStripeLrgHLAVPRSHF19",
                        "link":"\/product\/369936",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"304954",
                        "name":"Grey",
                        "has_parent_sku":true,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairGreyLrgAVF19_zmGRweb_HWGrouperThumb200516040951NodChairGreyLrgAVF19_zmGR.jpgNodChairGreyLrgAVF19_zmGR.jpg",
                        "image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/isimageCrateNodChairGreyLrgPRSHF19NodChairGreyLrgPRSHF19",
                        "link":"\/product\/304954",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"303280",
                        "name":"Mint",
                        "has_parent_sku":false,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairMintLrgAVF19_zmGRweb_HWGrouperThumb200516060032NodChairMintLrgAVF19_zmGR.jpgNodChairMintLrgAVF19_zmGR.jpg",
                        "image":null,
                        "link":"\/product\/370015",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"303361",
                        "name":"Light Purple",
                        "has_parent_sku":false,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairLtPurpleLrgAVF19_zmGRweb_HWGrouperThumb200513040501NodChairLtPurpleLrgAVF19_zmGR.jpgNodChairLtPurpleLrgAVF19_zmGR.jpg",
                        "image":null,
                        "link":"\/product\/370015",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"305075",
                        "name":"Dark Green",
                        "has_parent_sku":true,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairDrkGreenLrgAVF19_zmGRweb_HWGrouperThumb200513040501NodChairDrkGreenLrgAVF19_zmGR.jpgNodChairDrkGreenLrgAVF19_zmGR.jpg",
                        "image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/isimageCrateNodChairDrkGreenLrgPRSHF19NodChairDrkGreenLrgPRSHF19",
                        "link":"\/product\/305075",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"303256",
                        "name":"Dark Blue",
                        "has_parent_sku":false,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairDrkBlueLrgAVF19_zmGRweb_HWGrouperThumb200509074447NodChairDrkBlueLrgAVF19_zmGR.jpgNodChairDrkBlueLrgAVF19_zmGR.jpg",
                        "image":null,
                        "link":"\/product\/370015",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"303276",
                        "name":"Pink",
                        "has_parent_sku":false,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairPinkLrgAVF19_zmGRweb_HWGrouperThumb200414083052NodChairPinkLrgAVF19_zmGR.jpgNodChairPinkLrgAVF19_zmGR.jpg",
                        "image":null,
                        "link":"\/product\/370015",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"303345",
                        "name":"Orange",
                        "has_parent_sku":false,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairOrangeLrgAVF19_zmGRweb_HWGrouperThumb200516060032NodChairOrangeLrgAVF19_zmGR.jpgNodChairOrangeLrgAVF19_zmGR.jpg",
                        "image":null,
                        "link":"\/product\/370015",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"621888",
                        "name":"Dark Grey Outer Space",
                        "has_parent_sku":false,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/OuterSpaceNodChrLrgPrsSHF18_zmGRweb_HWGrouperThumb200516060132OuterSpaceNodChrLrgPrsSHF18_zmGR.jpgOuterSpaceNodChrLrgPrsSHF18_zmGR.jpg",
                        "image":null,
                        "link":"\/product\/370015",
                        "is_button":false,
                        "label":null
                     },
                     {
                        "product_sku":"370015",
                        "variation_sku":"370015",
                        "name":"Blue Triangle",
                        "has_parent_sku":true,
                        "swatch_image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/NodChairBlueTriangleLgSHF19_zmGRweb_HWGrouperThumb200516055916NodChairBlueTriangleLgSHF19_zmGR.jpgNodChairBlueTriangleLgSHF19_zmGR.jpg",
                        "image":"https:\/\/www.lazysuzy.com\/cnb\/images-new\/isimageCrateNodChairBlueTriangleLgHLSHF19NodChairBlueTriangleLgHLSHF19",
                        "link":"\/product\/370015",
                        "is_button":false,
                        "label":null
                     }
                  ]
               },
            ]
         });
    }

    ngOnDestroy() {
        this.unsubscribe$.next(true);
        this.unsubscribe$.complete();
    }

}
