export const mockProductsAdd = [
    {
        "id": 3,
        "sku": "aston-leather-sofa-86-5-h4745",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Aston Leather Sofa (86.5\")",
        "product_url": "https://www.westelm.com/products/aston-leather-sofa-86-5-h4745/",
        "product_detail_url": "https://www.lazysuzy.com/product/aston-leather-sofa-86-5-h4745",
        "is_price": "2399",
        "was_price": "2399",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "gray,brown,white",
        "collection": "",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/aston-leather-sofa-86-5-h4745_11_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "haven-sofa-84-h3421",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Haven Sofa (84\")",
        "product_url": "https://www.westelm.com/products/haven-sofa-84-h3421/",
        "product_detail_url": "https://www.lazysuzy.com/product/haven-sofa-84-h3421",
        "is_price": "1599-2099",
        "was_price": "1599-2099",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "natural,gray,blue,black,green,brown,tan,pink,red,orange,yellow,silver,white,beige",
        "collection": "Haven Upholstered Collection",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/haven-sofa-84-h3421_5_xbg.png.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "paidge-sofa-h211",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Paidge Sofa (72.5\")",
        "product_url": "https://www.westelm.com/products/paidge-sofa-h211/",
        "product_detail_url": "https://www.lazysuzy.com/product/paidge-sofa-h211",
        "is_price": "859.99-1499",
        "was_price": "999-1499",
        "percent_discount": "13.91",
        "model_code": null,
        "color": "blue,gray,natural,brown,black,green,pink,red,orange,yellow,silver,white,beige,tan",
        "collection": "Paidge Upholstered Collection",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/paidge-sofa-h211_7_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "harmony-sofa-h2479",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Harmony Sofa (82\")",
        "product_url": "https://www.westelm.com/products/harmony-sofa-h2479/",
        "product_detail_url": "https://www.lazysuzy.com/product/harmony-sofa-h2479",
        "is_price": "1699-2099",
        "was_price": "1699-2099",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "natural,gray,white,blue,black,green,brown,pink,red,orange,yellow,silver,beige,tan",
        "collection": "Harmony Upholstered Collection",
        "condition": "![](https://www.westelm.com/weimgs/ab/images/i/202003/0074/images/pip/dream-\npip/icon-flat-rate-deli",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/harmony-sofa-h2479_5_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "eddy-sofa-h2078",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Eddy Sofa (82\")",
        "product_url": "https://www.westelm.com/products/eddy-sofa-h2078/",
        "product_detail_url": "https://www.lazysuzy.com/product/eddy-sofa-h2078",
        "is_price": "999-1099",
        "was_price": "999-1099",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "black,gray,white,tan,red,blue",
        "collection": "Eddy Upholstered Collection",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/eddy-sofa-h2078_10_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "urban-sofa-h1431",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Urban Sofa (84.5\")",
        "product_url": "https://www.westelm.com/products/urban-sofa-h1431/",
        "product_detail_url": "https://www.lazysuzy.com/product/urban-sofa-h1431",
        "is_price": "1119.3-1899",
        "was_price": "1499-1899",
        "percent_discount": "25.33",
        "model_code": null,
        "color": "gray,blue,natural,black,green,brown,pink,red,orange,yellow,silver,white,beige,tan",
        "collection": "Urban Upholstered Collection",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/urban-sofa-h1431_10_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "qs-axel-leather-sofa-76-h2519",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Axel Leather Sofa (76\")",
        "product_url": "https://www.westelm.com/products/qs-axel-leather-sofa-76-h2519/",
        "product_detail_url": "https://www.lazysuzy.com/product/qs-axel-leather-sofa-76-h2519",
        "is_price": "2799-2899",
        "was_price": "2799-2899",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "blue,gray,green,black,white,brown,natural",
        "collection": "Axel Leather Collection",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/qs-axel-leather-sofa-76-h2519_10_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "harris-sofa-76-h4612",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Harris Sofa (76\")",
        "product_url": "https://www.westelm.com/products/harris-sofa-76-h4612/",
        "product_detail_url": "https://www.lazysuzy.com/product/harris-sofa-76-h4612",
        "is_price": "999-1399",
        "was_price": "999-1399",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "gray,blue,black,green,brown,natural,pink,red,orange,yellow,silver,white,beige,tan",
        "collection": "Harris Upholstered Collection",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/harris-sofa-76-h4612_7_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "denmark-loveseat-h1814",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Denmark Leather Sofa (66\")",
        "product_url": "https://www.westelm.com/products/denmark-loveseat-h1814/",
        "product_detail_url": "https://www.lazysuzy.com/product/denmark-loveseat-h1814",
        "is_price": "1799-2499",
        "was_price": "1799-2499",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "gray,brown,blue,white",
        "collection": "",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/denmark-loveseat-h1814_11_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "dekalb-leather-sofa-h271",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Dekalb Leather Sofa (85\")",
        "product_url": "https://www.westelm.com/products/dekalb-leather-sofa-h271/",
        "product_detail_url": "https://www.lazysuzy.com/product/dekalb-leather-sofa-h271",
        "is_price": "2309.3-3599",
        "was_price": "3299-3599",
        "percent_discount": "30.00",
        "model_code": null,
        "color": "gray,brown,blue,green,black,white,red,natural",
        "collection": "Dekalb Leather Collection",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/dekalb-leather-sofa-h271_11_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "urban-leather-sofa-h2496",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Urban Leather Sofa (84.5\")",
        "product_url": "https://www.westelm.com/products/urban-leather-sofa-h2496/",
        "product_detail_url": "https://www.lazysuzy.com/product/urban-leather-sofa-h2496",
        "is_price": "2399-3299",
        "was_price": "2399-3299",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "blue,gray,green,red,brown,white",
        "collection": "Urban Leather Collection",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/urban-leather-sofa-h2496_7_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "drake-sofa-76-h2859",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Drake Sofa (76\")",
        "product_url": "https://www.westelm.com/products/drake-sofa-76-h2859/",
        "product_detail_url": "https://www.lazysuzy.com/product/drake-sofa-76-h2859",
        "is_price": "1099-1499",
        "was_price": "1099-1499",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "blue,gray,black,green,brown,natural,pink,red,orange,yellow,silver,white,beige,tan",
        "collection": "Drake Upholstered Collection",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/drake-sofa-76-h2859_18_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "birch-loveseat-h4401",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "The Floyd Sofa (60.5\")",
        "product_url": "https://www.westelm.com/products/birch-loveseat-h4401/",
        "product_detail_url": "https://www.lazysuzy.com/product/birch-loveseat-h4401",
        "is_price": "1095-1395",
        "was_price": "1095-1395",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "blue",
        "collection": "",
        "condition": "**Shipping + Delivery**\n\nYour order will be shipped directly from Floyd's warehouse 1-5 business day",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/birch-loveseat-h4401_1_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "drake-leather-sofa-76-h3820",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Drake Leather Sofa (76\")",
        "product_url": "https://www.westelm.com/products/drake-leather-sofa-76-h3820/",
        "product_detail_url": "https://www.lazysuzy.com/product/drake-leather-sofa-76-h3820",
        "is_price": "2799-2999",
        "was_price": "2799-2999",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "gray,green,black,white,red,natural,brown",
        "collection": "Drake Leather Collection",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/drake-leather-sofa-76-h3820_1_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "leon-wood-frame-leather-loveseat-68-h2742",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Leon Wood Frame Leather Sofa (68\")",
        "product_url": "https://www.westelm.com/products/leon-wood-frame-leather-loveseat-68-h2742/",
        "product_detail_url": "https://www.lazysuzy.com/product/leon-wood-frame-leather-loveseat-68-h2742",
        "is_price": "2499-2699",
        "was_price": "2499-2699",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "blue,gray,green,black,white,red,natural,brown",
        "collection": "",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/leon-wood-frame-leather-loveseat-68-h2742_2_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 4,
        "sku": "541136",
        "is_new": false,
        "redirect": false,
        "site": "World Market",
        "name": "Quentin Chesterfield Sofa",
        "product_url": "https://www.tkqlhce.com/click-8945510-13226176?url=https://www.worldmarket.com/product/charcoal-gray-quentin-chesterfield-sofa.do",
        "product_detail_url": "https://www.lazysuzy.com/product/541136",
        "is_price": "749.99",
        "was_price": "749.99",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "Gray",
        "collection": null,
        "condition": null,
        "main_image": "https://www.lazysuzy.com/nw/xbg/69445_XXX_v2.tif_wid=480_cvt=jpeg_xbg.png",
        "reviews": 130,
        "rating": 4.8,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "bliss-sofa-g494",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Bliss Sofa (79.5\")",
        "product_url": "https://www.westelm.com/products/bliss-sofa-g494/",
        "product_detail_url": "https://www.lazysuzy.com/product/bliss-sofa-g494",
        "is_price": "1399-1899",
        "was_price": "1399-1899",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "blue,gray,black,green,brown,natural,red,orange,pink,white,tan",
        "collection": "Bliss Upholstered Collection",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/bliss-sofa-g494_7_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "sloane-leather-sofa-78-h2925",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Sloane Leather Sofa (78\")",
        "product_url": "https://www.westelm.com/products/sloane-leather-sofa-78-h2925/",
        "product_detail_url": "https://www.lazysuzy.com/product/sloane-leather-sofa-78-h2925",
        "is_price": "1999-2099",
        "was_price": "1999-2099",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "blue,gray,green,black,white,natural",
        "collection": "Sloane Leather Collection",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/sloane-leather-sofa-78-h2925_7_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "henry-sofa-86-h2525",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Henry® Sofa (86\")",
        "product_url": "https://www.westelm.com/products/henry-sofa-86-h2525/",
        "product_detail_url": "https://www.lazysuzy.com/product/henry-sofa-86-h2525",
        "is_price": "699.3-1299",
        "was_price": "999-1299",
        "percent_discount": "30.00",
        "model_code": null,
        "color": "blue,gray,natural,white,black,green,brown,pink,red,orange,yellow,silver,beige,tan",
        "collection": "Henry Upholstered Collection",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/henry-sofa-86-h2525_5_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "andes-leather-sofa-765-h2647",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Andes Leather Sofa (76.5\")",
        "product_url": "https://www.westelm.com/products/andes-leather-sofa-765-h2647/",
        "product_detail_url": "https://www.lazysuzy.com/product/andes-leather-sofa-765-h2647",
        "is_price": "2399-3299",
        "was_price": "2399-3299",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "blue,gray,green,red,brown,white",
        "collection": "Andes Leather Collection",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/andes-leather-sofa-765-h2647_7_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "leon-wood-frame-leather-sofa-82-h2741",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Leon Wood Frame Leather Sofa (82\")",
        "product_url": "https://www.westelm.com/products/leon-wood-frame-leather-sofa-82-h2741/",
        "product_detail_url": "https://www.lazysuzy.com/product/leon-wood-frame-leather-sofa-82-h2741",
        "is_price": "2999-3199",
        "was_price": "2999-3199",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "blue,gray,green,black,white,red,natural,brown",
        "collection": "",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/leon-wood-frame-leather-sofa-82-h2741_2_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "wing-loveseat-h4837",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Wing Sofa (51\")",
        "product_url": "https://www.westelm.com/products/wing-loveseat-h4837/",
        "product_detail_url": "https://www.lazysuzy.com/product/wing-loveseat-h4837",
        "is_price": "899-999",
        "was_price": "899-999",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "blue,gray,black,yellow,multicolor,brown",
        "collection": "",
        "condition": "**Shipping + Delivery**\n\nPlease enter your zip code on the product page or in cart for a delivery da",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/wing-loveseat-h4837_2_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "carlo-mid-century-sofa-h2653",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Carlo Mid-Century Sofa (77.5\")",
        "product_url": "https://www.westelm.com/products/carlo-mid-century-sofa-h2653/",
        "product_detail_url": "https://www.lazysuzy.com/product/carlo-mid-century-sofa-h2653",
        "is_price": "1199-1599",
        "was_price": "1199-1599",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "blue,gray,black,brown,natural,tan,pink,green,red,orange,yellow,silver,beige,white",
        "collection": "Carlo Mid-Century Collection",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/carlo-mid-century-sofa-h2653_10_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    },
    {
        "id": 3,
        "sku": "antwerp-loveseat-h2297",
        "is_new": false,
        "redirect": false,
        "site": "West Elm",
        "name": "Antwerp Sofa (76\")",
        "product_url": "https://www.westelm.com/products/antwerp-loveseat-h2297/",
        "product_detail_url": "https://www.lazysuzy.com/product/antwerp-loveseat-h2297",
        "is_price": "1499-1799",
        "was_price": "1499-1799",
        "percent_discount": "0.00",
        "model_code": null,
        "color": "blue,gray,brown,natural,red,yellow,orange,silver,beige,black,white,tan",
        "collection": "",
        "condition": "**UNLIMITED FLAT RATE DELIVERY – FURNITURE + OVERSIZED ITEMS**\n\nOur Flat Rate Delivery fees are base",
        "main_image": "https://www.lazysuzy.com/westelm/xbg/antwerp-loveseat-h2297_5_xbg.png",
        "reviews": 0,
        "rating": 0,
        "wishlisted": false
    }
];